name: nsg_biolab_booking_app
description: A booking app.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  api:
    path: packages/api
  bloc: ^8.1.0
  dio: ^4.0.6
  image_picker: ^0.8.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_config: ^2.0.0
  http: ^0.13.5
  intl: ^0.17.0
  pull_to_refresh: ^2.0.0
  shared_preferences: ^2.0.15
  repository:
    path: packages/repository
  shared_ui:
    path: packages/shared_ui
  domain:
    path: packages/domain
  flutter_launcher_icons: ^0.11.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "packages/shared_ui/lib/assets/images/app_icon.png"

flutter:
  uses-material-design: true
